### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by therocketforever** [therocketforever/guns.for.hire#5]
Yup. exactly that.

**Comment by therocketforever** [comment]
I have Spellchecked & grammar checked once already. I would just like you to confirm that I did not miss anything before I start sending this guy out. I checked each of the files in `assets/` so  I'm pretty sure its good to go. You don't have to go to that depth. you can probably just double check against `build/cv.md` and that should be good.

**Comment by markpoon** [comment]
Okay, nevermind, got it.

Wait... hold on... these branches are no longer on remote...

the versions that are up have not been looked through, my previous notes are still there in dev.projects. anything in #{ } is something I need you to fill in with how you would say it.

**Comment by therocketforever** [comment]
You should pull then. Cause your right. I have merged all of the asset topic branches in to `development`. I left the `.mark` branches although they may no longer be relevant.

**Comment by therocketforever** [comment]
also, maybe ammend notes to the end of the paragraph or something, or just change the txt to what you would say. cause when you wrap it inline in `#{}` it gettin striped out buy the rake task when I blow away the kramdown directives, also I noticed that even though nothing happens, when the line is manipulated with a `#{}` in it the interpreter is trying to interpolate the string.

**Comment by markpoon** [comment]
Hehe, I'm testing out edge cases! I won't be adding more now, I retread I last night and its looking good, I have two more and ill push it up.

**Comment by therocketforever** [comment]
spellchecked
